### PR TITLE
Add UI layout/fragment

### PR DESCRIPTION
**Pull request by CharlotteZsm**
#34

### CODE REVIEW

**Comment by ysrivast2000** [comment]
Hey Charlotte, I was testing out the pull request but I'm not sure how to access the new follower and profile fragments with the app. Can you let me know how to get to them? This is what I see on the home screen with your branch: 
image

**Comment by CharlotteZsm** [comment]
> Hey Charlotte, I was testing out the pull request but I'm not sure how to access the new follower and profile fragments with the app. Can you let me know how to get to them? This is what I see on the home screen with your branch: image

I think Jonas will work on the home page. Also, I will change the three buttons at the bottom of the screen to make it same as what we did in UI mockup tomorrow (e.g. the pictures bottom)
FollowerMessages
.

**Comment by ysrivast2000** [comment]
Ok, sounds good 👍

**Comment by ysrivast2000** [comment]
Hey Charlotte I had an error when testing the PR (were those xml files deleted maybe?):
image

**Comment by ysrivast2000** [comment]
When you get the chance can you update this?

**Comment by CharlotteZsm** [comment]
> When you get the chance can you update this?

I fixed this. Sorry about that.

**Comment by ysrivast2000** [comment]
In the following, follower, and profile fragments theres a runtime issue on lines:( https://github.com/CMPUT301F21T20/HabitTracker/blob/e5821e561affbcff9ddfd6a01ac2d03f036f03a6/app/src/main/java/com/example/habittracker/ui/following/FollowingFragment.java#L36 , https://github.com/CMPUT301F21T20/HabitTracker/blob/e5821e561affbcff9ddfd6a01ac2d03f036f03a6/app/src/main/java/com/example/habittracker/ui/follower/FollowerFragment.java#L28 , https://github.com/CMPUT301F21T20/HabitTracker/blob/e5821e561affbcff9ddfd6a01ac2d03f036f03a6/app/src/main/java/com/example/habittracker/ui/profile/ProfileFragment.java#L29 )

**Comment by ysrivast2000** [comment]
image
 The error seems to happen when we try to ruin the getText() function on the view models

**Comment by ysrivast2000** [comment]
Also, can you update the branch with all the updates from main?

**Comment by CharlotteZsm** [comment]
> Also, can you update the branch with all the updates from main?

I am updating now and there is a problem. For these three parts, actually, I referenced the original three fragments, but I did not totally understand this part. Do you think they are useful in these files? Or I can delete them.

**Comment by ysrivast2000** [comment]
> > Also, can you update the branch with all the updates from main?
> 
> I am updating now and there is a problem. For these three parts, actually, I referenced the original three fragments, but I did not totally understand this part. Do you think they are useful in these files? Or I can delete them.

They shouldn't be

**Comment by CharlotteZsm** [comment]
> > > Also, can you update the branch with all the updates from main?
> > 
> > 
> > I am updating now and there is a problem. For these three parts, actually, I referenced the original three fragments, but I did not totally understand this part. Do you think they are useful in these files? Or I can delete them.
> 
> They shouldn't be

Then can I delete all three new viewmodels and the related functions in the three fragments(following, follower, profile)?

**Comment by ysrivast2000** [comment]
Oh sorry, I misunderstood your question earlier. We need those files.

**Comment by CharlotteZsm** [comment]
> Oh sorry, I misunderstood your question earlier. We need those files.

I think I understand a bit more on viewmodel. However, I think they cannot be completed by now since we do not have some lists like users. But I fixed the error by changing the function content to return.

**Comment by ysrivast2000** [comment]
Ok, we can just come back to this issue later then

**Comment by ysrivast2000** [comment]
On the profile page, the bottom nav bar is being duplicated:
image


Also there is no way to add any habits anymore

**Comment by ysrivast2000** [comment]
Oh also, can you make a separate pull request where the only change is for the README?

**Comment by CharlotteZsm** [comment]
> Oh also, can you make a separate pull request where the only change is for the README?

Hi Yash，did you finish checking this? Jonas said he needed this part

**Comment by ysrivast2000** [comment]
> > Oh also, can you make a separate pull request where the only change is for the README?
> 
> Hi Yash，did you finish checking this? Jonas said he needed this part

Hey Charlotte, sorry, didn't know there were updates here. It looks good now! Thanks for the updates. One final thing, can you merge your branch with the main, then I can merge this PR.

**Comment by CharlotteZsm** [comment]
> > > Oh also, can you make a separate pull request where the only change is for the README?
> > 
> > 
> > Hi Yash，did you finish checking this? Jonas said he needed this part
> 
> Hey Charlotte, sorry, didn't know there were updates here. It looks good now! Thanks for the updates. One final thing, can you merge your branch with the main, then I can merge this PR.

Ok, finished. You can merge now.

**Pull request merged**
